modLoader="javafml"
loaderVersion="[60,)"
license="MIT"
[[mods]]
modId="suprememc"
version="1.0.0"
displayName="SupremeMC"
authors="Patrick Goodwin"
description='''Description of SupremeMC mod.'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[60,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.10,)"
    ordering="NONE"
    side="BOTH"
